### ISSUE TITLE
[RFE] allow multiple non-interactive commands to be executed without a script file

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#109]
We have a need to run a series of ravshello commands in a separate utility.  

We would like to execute the ravshello commands like this:

$ ravshello -a '/blueprints ls; /apps ls'

Is there anyway to do this without using the -s FILE option ?

**Comment by ryran** [comment]
Hey @ajblum 
Yeah I actually had this in mind myself recently. Totally doable.

**Comment by ryran** [comment]
Here's how it's implemented in the latest version:

```
$ ravshello -V
ravshello v1.13.1 last mod 2017/02/01

$ ravshello -h | grep -A4 COMMANDS
  COMMANDS           If any additional cmdline args are present, the
                     interactive shell is skipped; instead each word will be
                     executed as a separate command (ensure each command is
                     quoted to protect from shell expansion!)

$ ravshello -aq 'cd /blueprints' refresh ls
Welcome to ravshello, a shell to provision & manage machines with Ravello!
  Using configfile-specified nick 'rsawhill' for nickname
  Logged in to Ravello as ADMIN

Refreshing all blueprint data . . . DONE!

o- blueprints ...................................................................... [152 blueprints]
  o- CEPH125-20160321-bp-mtomson_stage ............................. [Mary Tomson created 2016/09/09]
  o- CEPH125-RHCS2.0-RHOSP9-patrick ............................. [Adolfo Vazquez created 2016/12/02]
  <OUTPUT TRUNCATED>
$
```

In case it's not clear, each shell word is a separate command. Since `refresh` and `ls` were one-word commands, I didn't quote them, but you get the idea -- ravshello executed 3 commands there.

Another way we could approach this is by splitting cmds on a semicolon character. That's not as clean because there's always the possibility that some command uses semicolons ... so I don't really like that even though it would make life a little easier for users. Let me know what you think @ajblum .

**Comment by ryran** [comment]
PS: It's also worth noting that the same behavior could have been had by simply `ravshello -aq /blueprints refresh ls` because a directory path as a single command is interpreted as if `cd` was used.

**Comment by ryran** [comment]
@ajblum I decided to differentiate parsing of argv a bit from the script-file option -- it now dumps you into the interactive shell after running the commands (unless one of your commands is `exit`).

**Comment by ryran** [comment]
I'll take the heart to mean you're happy with things as they are now. Of course hit me back if you have other suggestions.
