### ISSUE TITLE
[RFE] Use "regionDisplayName" instead of "regionName" for publishing apps and "regionName" instead of "regionId" when querying deployed apps

### ISSUE THREAD

**Issue by ajblum** [ryran/ravshello#145]
The new `oracle-ravello cloud <REGION>` regions names are not specific enough for our learners.  The older names included names of cities/states that are more recognizable.

Can we have ravshello default to only present the older region names based on this mapping:

https://mojo.redhat.com/docs/DOC-979522#jive_content_id_Launch_an_Application_from_a_Blueprint

The issue we recently hit is that Amazon Mumbai was added but only is available via "oracle-ravello-cloud ap-south-1" .  Our learners are not aware that this is the Mumbai region and should be preferred for those close to Mumbai.

**Comment by ryran** [comment]
Updated title to reflect what we decided to do here.

Changes:

- The `region=` argument to the `/apps new` and `/apps/APP publish` commands will still accept the canonical "regionName" (e.g., `ap-south-1`, `sa-east-1`); however, tab-completion will only provide suggestions based on the "regionDisplayName" field, with spaces converted to dashes (e.g., `Mumbai`, `Sao-Paulo`).
- The interactive publishing provided by the `/apps new` and `/apps/APP publish` commands will likewise only show the same "regionDisplayName" field (with spaces converted to dashes).
- Similarly, the region displayed when using `ls` in `/apps` or when using the `/apps/APP query_status` command has been updated to match.
- Finally, regions tagged with `deprecated: true` (all the ones that expose whether they're Amazon or Google) are now longer allowed by the `/apps new` and `/apps/APP publish` commands.
  * They're already deprecated because Ravello is planning to remove them (a not-necessarily-exhaustive list of examples: `us-central1`, `europe-west1`, `Virginia`, `Oregon`, `Ireland`, `Sao Paulo`, `Singapore`, `Tokyo 1`, `Sydney`) and the "regionDisplayName" for some of them conflicts with the "regionDisplayName" for the newer non-deprecated "Oracle Ravello Cloud" choices.
